name: dotnet-mac

on:
  push:
    branches: [ ci-mac ]

  pull_request:
    branches: [ ci-mac ]

jobs:
  build:

    runs-on: macos-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
    - uses: actions/checkout@v2

    - name: setup sdk
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.*

    - name: dependencies
      run: dotnet restore

    - name: build
      run: dotnet build --configuration Release --no-restore

    - name: units
      run: dotnet test units --no-restore --verbosity normal

    - name: earth
      run: dotnet test earth --no-restore --verbosity normal
