name: dotnet-core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup sdk
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: dependencies
      run: dotnet restore

    - name: build
      run: dotnet build --configuration Release --no-restore

    - name: units
      run: dotnet test units --no-restore --verbosity normal

    - name: earth
      run: dotnet test earth --no-restore --verbosity normal
